### ISSUE TITLE
Library and history page frontend implementation

### ISSUE THREAD

**Issue by HillaryWebb-coder** [zuri-training/Col-films-Team-120#22]
Implement the frontend design for the Library and history pages

**Comment by Bolajiomo99** [comment]
Check replit for the preview of the history page and I'll update with the images david forward to me to replace the logo, video, and icons. https://historylibrary-pages.bolajijs.repl.co/

**Comment by Bolajiomo99** [comment]
I'll push the files to the repository soon.

**Comment by Bolajiomo99** [comment]
https://github.com/zuri-training/Col-films-Team-120/commit/7f88cce75800f5a233aafc686005d7cb82ced0f8, I'll have to convert all the images david sent to me to png in order to use it for the landing pages. I'll update this soon because i'm still working on it presently and i need you to check what we can do to solve the container code. Once i'm through with history library will be very simple to create.
